nameOverride: ""

fullnameOverride: ""

# Kept for compatibility while refactoring
jitsu:
  environment: {}

# Common configuration values shared across multiple components.
config:
  # Postgres database URL in the format of: postgres://username:password@host:port/database?options
  # Will be configured automatically if left empty and using the PostgreSQL subchart.
  databaseURL: ""

  # Redis URL in the format of: redis://username:password@host:port
  # Will be configured automatically if left empty and using the Redis subchart.
  redisURL: ""

  # Global Kafka configuration
  kafkaBootstrapServers: ""
  kafkaSSL: ""
  kafkaSASL: "" # dict or string

  # Generate inter-service auth tokens automatically
  autoGenerateTokens: true

  # Use these values to override service URLs if deployed externally.
  bulkerURL: ""
  rotorURL: ""

global:
  postgresql:
    auth:
      username: "jitsu"
      password: ""
      database: "jitsu"
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

console:
  enabled: true
  config:
    # The URL where the Jitsu Console will be available
    # https://docs.jitsu.com/self-hosting/configuration#jitsu_public_url
    jitsuPublicURL: ""

    # Comma-separated list of email:password, required when not using GitHub OAuth
    # https://docs.jitsu.com/self-hosting/configuration#admin_credentials
    adminCredentials: ""

    # Enable GitHub OAuth
    # https://docs.jitsu.com/self-hosting/configuration#github_client_id
    githubClientID: ""
    githubClientSecret: ""

    # Disable sign-up
    # https://github.com/jitsucom/jitsu/blob/newjitsu/docker/README.md#further-steps
    disableSignup: "false"

    # Leave empty to configure automatically
    # https://docs.jitsu.com/self-hosting/configuration#console_auth_tokens
    consoleAuthTokens: ""

    # Leave empty to configure automatically
    # https://docs.jitsu.com/self-hosting/configuration#global_hash_secret
    globalHashSecret: ""

    # Plain, non-hashed tokens. Not recommended for production.
    # https://docs.jitsu.com/self-hosting/configuration#console_raw_auth_tokens
    consoleRawAuthTokens: ""

    # Leave empty to use global jitsu.databaseURL
    # https://docs.jitsu.com/self-hosting/configuration#database_url
    databaseURL: ""

    # Only needed if the bulker is deployed outside of this chart. Leave empty to configure automatically.
    # https://docs.jitsu.com/self-hosting/configuration#bulker_url-1
    bulkerURL: ""

    # Leave empty to configure automatically.
    # https://docs.jitsu.com/self-hosting/configuration#bulker_auth_key-1
    bulkerAuthKey: ""

    # Leave empty to configure automatically.
    # https://docs.jitsu.com/self-hosting/configuration#rotor_url
    rotorURL: ""

    # Public domain where ingest service is available. Leave empty to configure automatically.
    # https://docs.jitsu.com/self-hosting/configuration#ingest_host
    ingestHost: ""

    # HTTP port of the ingest service. Leave empty to configure automatically.
    # https://docs.jitsu.com/self-hosting/configuration#ingest_port
    ingestPort: ""

    # Whether to enable the Connectors Syncs feature in the Jitsu Console UI. Leave empty to configure automatically.
    # https://docs.jitsu.com/self-hosting/configuration#syncs_enabled
    syncsEnabled: ""

    # The URL of the Syncctl service. Leave empty to configure automatically.
    # https://docs.jitsu.com/self-hosting/configuration#syncctl_url
    syncctlUrl: ""

    # Leave empty to configure automatically.
    # https://docs.jitsu.com/self-hosting/configuration#syncctl_auth_key
    syncctlAuthKey: ""

    # Enables Connectors Sync Scheduler feature. Google Service Account Key in JSON format.
    # https://docs.jitsu.com/self-hosting/configuration#syncctl_auth_key
    googleSchedulerKey: ""

    # ClickHouse configuration
    # https://docs.jitsu.com/self-hosting/configuration#clickhouse_metrics_schema
    clickhouseMetricsSchema: ""
    clickhouseURL: ""
    clickhouseUsername: ""
    clickhousePassword: ""

    # Log format. One of "text", "json".
    # https://docs.jitsu.com/self-hosting/configuration#log_format-1
    logFormat: "text"
  replicaCount: 1
  image:
    repository: jitsucom/console
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    className: ''
    annotations: {}
    hosts: []
      - host: jitsu.example.org
        paths:
          - path: /
            pathType: Prefix
    tls: []
    # - secretName: jitsu-example-org-tls
    #   hosts:
    #     - jitsu.example.org
  probes:
    enabled: true
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
  environment: {}
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

bulker:
  enabled: true
  config:
    # UUID of bulker instance
    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_instance_id
    bulkerInstanceID: ""

    # Leave empty to configure automatically.
    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_config_source
    bulkerConfigSource: ""

    # Leave empty to configure automatically.
    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_config_source_http_auth_token
    bulkerConfigSourceHTTPAuthToken: ""

    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_config_refresh_period_sec
    bulkerConfigRefreshPeriodSec: ""

    # Dict of dicts converted to JSON environment variables, e.g.:
    # bulkerDestination:
    #   postgres:
    #     id: postgres
    # results in: BULKER_DESTINATION_POSTGRES='{"id": "postgres"}'
    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#with-bulker_destination_-environment-variables
    bulkerDestination: {}

    # Leave empty to automatically configure.
    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_auth_tokens
    bulkerAuthTokens: ""

    # Leave empty to automatically configure.
    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_token_secret
    bulkerTokenSecret: ""

    # Leave empty to automatically configure.
    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_raw_auth_tokens
    bulkerRawAuthTokens: ""

    # Leave empty to automatically configure.
    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_kafka_bootstrap_servers
    bulkerKafkaBootstrapServers: ""

    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_kafka_ssl
    bulkerKafkaSSL: "false"

    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_kafka_ssl_skip_verify
    bulkerKafkaSSLSkipVerify: ""

    # Can be either a string or a dict.
    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_kafka_sasl-aka-kafka-auth
    bulkerKafkaSASL: ""

    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_batch_runner_default_period_sec
    bulkerBatchRunnerDefaultPeriodSec: ""

    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_batch_runner_default_batch_size
    bulkerBatchRunnerDefaultBatchSize: ""

    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_messages_retry_count
    bulkerMessagesRetryCount: ""

    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_messages_retry_backoff_base
    bulkerMessagesRetryBackoffBase: ""

    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_messages_retry_backoff_max_delay
    bulkerMessagesRetryBackoffMaxDelay: ""

    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_batch_runner_default_retry_period_sec
    bulkerBatchRunnerDefaultRetryPeriodSec: ""

    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_batch_runner_default_retry_batch_size
    bulkerBatchRunnerDefaultRetryBatchSize: ""

    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_kafka_topic_retention_hours
    bulkerKafkaTopicRetentionHours: ""

    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_kafka_retry_topic_retention_hours
    bulkerKafkaRetryTopicRetentionHours: ""

    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_kafka_dead_topic_retention_hours
    bulkerKafkaDeadTopicRetentionHours: ""

    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#bulker_kafka_topic_replication_factor
    bulkerKafkaTopicReplicationFactor: ""

    # Store history of processed events in Redis. Leave empty to configure automatically if config.redisURL is set and/or Redis subchart is being used.
    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#connection-to-redis-optional
    bulkerRedisURL: ""

    # https://github.com/jitsucom/bulker/blob/main/.docs/server-config.md#connection-to-redis-optional
    bulkerEventsLogMaxSize: ""
  replicaCount: 1
  image:
    repository: jitsucom/bulker
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  service:
    type: ClusterIP
    port: 3042
  probes:
    enabled: true
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
  environment: {}
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

rotor:
  enabled: true
  config:
    # Leave empty to configure automatically.
    # https://docs.jitsu.com/self-hosting/configuration#repository_base_url
    repositoryBaseURL: ""

    # Leave empty to configure automatically.
    # https://docs.jitsu.com/self-hosting/configuration#repository_auth_token
    repositoryAuthToken: ""

    # https://docs.jitsu.com/self-hosting/configuration#repository_refresh_period_sec
    repositoryRefreshPeriodSec: ""

    # Leave empty to configure automatically if config.redisURL is set or Redis subchart is being used.
    # https://docs.jitsu.com/self-hosting/configuration#redis_url
    redisURL: ""

    # Leave empty to configure automatically.
    # https://docs.jitsu.com/self-hosting/configuration#bulker_url
    bulkerURL: ""

    # Leave empty to configure automatically.
    # https://docs.jitsu.com/self-hosting/configuration#bulker_auth_key
    bulkerAuthKey: ""

    # Leave empty to configure automatically if config.kafkaBootstrapServers is set or Kafka subchart is being used.
    # https://docs.jitsu.com/self-hosting/configuration#kafka_bootstrap_servers
    kafkaBootstrapServers: ""

    # https://docs.jitsu.com/self-hosting/configuration#kafka_ssl
    kafkaSSL: "false"

    # Can be either a string or a dict.
    # https://docs.jitsu.com/self-hosting/configuration#kafka_sasl-aka-kafka-auth
    kafkaSASL: ""

    # Leave empty to configure automatically if MongoDB subchart is being used.
    # https://docs.jitsu.com/self-hosting/configuration#mongodb_url
    mongodbURL: ""

    # https://docs.jitsu.com/self-hosting/configuration#metrics_destination_id
    metricsDestinationID: ""

    # https://docs.jitsu.com/self-hosting/configuration#events_log_max_size
    eventsLogMaxSize: ""

    # https://docs.jitsu.com/self-hosting/configuration#concurrency
    concurrency: ""

    # https://docs.jitsu.com/self-hosting/configuration#messages_retry_count
    messagesRetryCount: ""

    # https://docs.jitsu.com/self-hosting/configuration#messages_retry_backoff_base
    messagesRetryBackoffBase: ""

    # https://docs.jitsu.com/self-hosting/configuration#messages_retry_backoff_max_delay
    messagesRetryBackoffMaxDelay: ""

    # https://docs.jitsu.com/self-hosting/configuration#log_format
    logFormat: "text"
  replicaCount: 1
  image:
    repository: jitsucom/rotor
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 3401
  probes:
    enabled: true
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  environment: {}
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

ingest:
  enabled: true
  replicaCount: 1
  image:
    repository: jitsucom/ingest
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 3043
  ingress:
    enabled: true
    className: ''
    annotations: {}
    hosts: []
      - host: jitsu.example.org
        paths:
          - path: /api/s/
            pathType: Prefix
    tls: []
    # - secretName: jitsu-example-org-tls
    #   hosts:
    #     - jitsu.example.org
  probes:
    enabled: true
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
  environment:
    INGEST_PUBLIC_URL:
      value: ""
    INGEST_AUTH_TOKENS:
      # https://docs.jitsu.com/self-hosting/configuration#ingest_auth_tokens
      value: ""
    INGEST_KAFKA_BOOTSTRAP_SERVERS:
      # host:port
      value: ""
    INGEST_REPOSITORY_URL:
      value: "http://jitsu-console:3000/api/admin/export/streams-with-destionations"
    INGEST_REPOSITORY_AUTH_TOKEN:
      # https://docs.jitsu.com/self-hosting/configuration#console_auth_tokens
      # service-admin-account:console-token
      value: ""
    INGEST_SCRIPT_ORIGIN:
      value: "http://jitsu-console:3000/api/s/javascript-library"
    INGEST_ROTOR_URL:
      value: "http://jitsu-rotor:3401"
    INGEST_REDIS_URL:
      value: ""
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

syncctl:
  enabled: true
  replicaCount: 1
  image:
    repository: jitsucom/syncctl
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 3043
  probes:
    enabled: true
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
  environment:
    SYNCCTL_AUTH_TOKENS:
      value: ""
    SYNCCTL_TOKEN_SECRET:
      value: ""
    SYNCCTL_DATABASE_URL:
      value: ""
    SYNCCTL_KUBERNETES_CLIENT_CONFIG:
      value: local
    SYNCCTL_KUBERNETES_CONTEXT:
      value: ""
    SYNCCTL_KUBERNETES_NAMESPACE:
      # This needs to be abstracted
      value: '{{ .Release.Namespace }}'
    SYNCCTL_BULKER_URL:
      value: "http://jitsu-bulker:3042"
    SYNCCTL_BULKER_AUTH_KEY:
      value: ""
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

migration:
  enabled: true
  image:
    repository: jitsucom/console
    pullPolicy: IfNotPresent
    tag: "latest"
  restartPolicy: Never
  environment: {}
  jobAnnotations: {}
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

postgresql:
  enabled: true

redis:
  enabled: true

kafka:
  enabled: true
  listeners:
    interbroker:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    client:
      protocol: PLAINTEXT
      external: PLAINTEXT

mongodb:
  enabled: true
