apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsu.fullname" . }}-rotor
  labels:
    {{- include "jitsu.labels" . | nindent 4 }}
spec:
  {{- if not .Values.rotor.autoscaling.enabled }}
  replicas: {{ .Values.rotor.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "jitsu.selectorLabels" . | nindent 6 }}
      {{- include "jitsu.rotor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jitsu.selectorLabels" . | nindent 8 }}
        {{- include "jitsu.rotor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jitsu.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if or .Values.config.autoGenerateTokens .Values.redis.enabled .Values.console.enabled }}
      initContainers:
        {{- if .Values.config.autoGenerateTokens }}
        - name: wait-for-tokens
          image: ghcr.io/groundnuty/k8s-wait-for:v2.0
          args: ["job-wr", "{{ include "jitsu.fullname" . }}-auto-generate-tokens-{{ sha1sum (toJson .Values) | substr 0 8 }}"]
        {{- end }}
        {{- if .Values.redis.enabled }}
        - name: wait-for-redis
          image: ghcr.io/groundnuty/k8s-wait-for:v2.0
          args: ["service", "{{ include "jitsu.fullname" . }}-redis-master"]
        {{- end }}
        {{- if .Values.console.enabled }}
        - name: wait-for-console
          image: ghcr.io/groundnuty/k8s-wait-for:v2.0
          args: ["service", "{{ include "jitsu.fullname" . }}-console"]
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.rotor.image.repository }}:{{ .Values.rotor.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.rotor.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.rotor.service.port }}
              protocol: TCP
          {{- if .Values.rotor.probes.enabled }}
          livenessProbe:
            httpGet:
              port: http
              path: /health
          readinessProbe:
            httpGet:
              port: http
              path: /health
          {{- end }}
          env:
            {{- include "jitsu.rotor.env" . | nindent 12 }}
            {{- with .Values.rotor.env }}
            {{- toYaml .Values.rotor.env | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
