{{- if and .Values.tokenGenerator.enabled .Values.tokenGenerator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jitsu.tokenGenerator.serviceAccountName" . }}
  labels:
    {{- include "jitsu.labels" . | nindent 4 }}
  {{- with .Values.tokenGenerator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
