{{- if .Values.config.syncctl.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "jitsu.fullname" . }}-syncctl
  labels:
    {{- include "jitsu.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create","delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch","create","delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
{{- end }}
