{{- if and .Values.syncctl.serviceAccount.create .Values.syncctl.serviceAccount.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jitsu.syncctl.serviceAccountName" . }}
  labels:
    {{- include "jitsu.labels" . | nindent 4 }}
  {{- with .Values.syncctl.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
